#!/usr/bin/env bash
# Comrade Linux setup: Tauri needs WebKitGTK, ALSA, and native build tools.
# - With sudo: installs them with pacman, apt, or dnf.
# - Without sudo: vendors the Arch package into the comrade-agent home
#   ($COMRADE_HOME, else ~/.config/comrade-agent) and wires .cargo/config.toml
#   (PKG_CONFIG_PATH + linker search path + rpath).
set -euo pipefail

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "ERROR: scripts/setup-linux.sh is only for Linux; see README.md for macOS setup." >&2
    exit 1
fi

MIRROR="https://mirror.rackspace.com/archlinux/extra/os/x86_64"
COMRADE_HOME_DIR="${COMRADE_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/comrade-agent}"
SYSROOT="$COMRADE_HOME_DIR/sysroot"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if pkg-config --exists webkit2gtk-4.1 alsa 2>/dev/null \
    && command -v cc >/dev/null 2>&1 \
    && command -v cmake >/dev/null 2>&1; then
    echo "Linux native dependencies are already installed. Nothing to do."
    exit 0
fi

CAN_SUDO=false
if command -v sudo >/dev/null 2>&1; then
    if sudo -n true 2>/dev/null; then
        CAN_SUDO=true
    elif [[ -t 0 ]] && sudo -v; then
        CAN_SUDO=true
    fi
fi

if [[ "$CAN_SUDO" == true ]]; then
    if command -v pacman >/dev/null 2>&1; then
        echo "Installing native dependencies via pacman..."
        sudo pacman -S --needed --noconfirm base-devel pkgconf cmake clang webkit2gtk-4.1 alsa-lib
    elif command -v apt-get >/dev/null 2>&1; then
        echo "Installing native dependencies via apt..."
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config cmake clang libwebkit2gtk-4.1-dev libasound2-dev
    elif command -v dnf >/dev/null 2>&1; then
        echo "Installing native dependencies via dnf..."
        sudo dnf install -y gcc gcc-c++ make pkgconf-pkg-config cmake clang webkit2gtk4.1-devel alsa-lib-devel
    else
        echo "ERROR: unsupported package manager. Install WebKitGTK 4.1, ALSA development headers, a C/C++ compiler, pkg-config, CMake, and Clang." >&2
        exit 1
    fi
    exit 0
fi

if ! command -v pacman >/dev/null 2>&1; then
    echo "ERROR: rootless WebKit vendoring is supported only on Arch Linux." >&2
    echo "Install WebKitGTK 4.1, ALSA development headers, a C/C++ compiler, pkg-config, CMake, and Clang, then rerun this script." >&2
    exit 1
fi

for command_name in pkg-config cc cmake curl tar; do
    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "ERROR: missing required command: $command_name" >&2
        exit 1
    fi
done
if ! pkg-config --exists alsa 2>/dev/null; then
    echo "ERROR: ALSA development files are missing (Arch package: alsa-lib)." >&2
    exit 1
fi

# Consolidate a previous rootless install into the comrade-agent home.
if [[ ! -f "$SYSROOT/usr/lib/pkgconfig/webkit2gtk-4.1.pc" ]] \
    && [[ -f "$HOME/comrade-sysroot/usr/lib/pkgconfig/webkit2gtk-4.1.pc" ]]; then
    echo "Moving previous sysroot into $SYSROOT ..."
    mkdir -p "$COMRADE_HOME_DIR"
    mv "$HOME/comrade-sysroot" "$SYSROOT"
fi

if [[ ! -f "$SYSROOT/usr/lib/pkgconfig/webkit2gtk-4.1.pc" ]]; then
    echo "No sudo — fetching webkit2gtk-4.1 into $SYSROOT ..."
    mkdir -p "$SYSROOT"
    cd "$SYSROOT"
    PKG=$(curl -s "$MIRROR/" | grep -o 'webkit2gtk-4\.1-[^"]*\.pkg\.tar\.zst' | sort -u | tail -1)
    if [[ -z "$PKG" ]]; then
        echo "ERROR: could not find webkit2gtk-4.1 on $MIRROR" >&2
        exit 1
    fi
    if [[ ! -f "$PKG" ]]; then
        curl -sO "$MIRROR/$PKG"
    fi
    tar -xf "$PKG"
    if LD_LIBRARY_PATH="$SYSROOT/usr/lib" ldd usr/lib/libwebkit2gtk-4.1.so.0 | grep -q 'not found'; then
        echo "ERROR: missing transitive deps (see above). Install them or run with sudo." >&2
        exit 1
    fi
    cd "$REPO_ROOT"
else
    echo "Vendored webkit already present at $SYSROOT."
fi

mkdir -p "$REPO_ROOT/.cargo"
cat > "$REPO_ROOT/.cargo/config.toml" <<EOF
# Generated by scripts/setup-linux.sh — do not hand-edit.
[env]
PKG_CONFIG_PATH = "$SYSROOT/usr/lib/pkgconfig"

[build]
rustflags = [
    "-C", "link-arg=-L$SYSROOT/usr/lib",
    "-C", "link-arg=-Wl,-rpath,$SYSROOT/usr/lib",
    "-C", "link-arg=-Wl,-rpath,\$ORIGIN",
]
EOF

# Rootless WebKit helper shim (LD_PRELOAD redirect for the hard-coded
# /usr/lib/webkit2gtk-4.1 helper path). Only needed when the system copy
# is absent; the app re-execs itself under it automatically.
SHIM_SRC="$REPO_ROOT/shim/webkit-path-shim.c"
SHIM_OUT="$COMRADE_HOME_DIR/shim/webkit-shim.so"
if command -v cc >/dev/null 2>&1 && [[ -f "$SHIM_SRC" ]]; then
    mkdir -p "$(dirname "$SHIM_OUT")"
    cc -shared -fPIC -O2 -o "$SHIM_OUT" "$SHIM_SRC" -ldl \
        && echo "WebKit path shim built: $SHIM_OUT"
else
    echo "WARNING: no C compiler — WebKit shim not built (needs: sudo pacman -S webkit2gtk-4.1)" >&2
fi
echo "Sysroot ready. Build with: cargo build -p comrade-desktop"
