#!/usr/bin/env bash
# Comrade Linux setup: Tauri needs webkit2gtk-4.1 system libs.
# - With sudo: installs from pacman (preferred).
# - Without sudo: vendors the Arch package into the comrade-agent home
#   ($COMRADE_HOME, else ~/.config/comrade-agent) and wires .cargo/config.toml
#   (PKG_CONFIG_PATH + linker search path + rpath).
set -euo pipefail

MIRROR="https://mirror.rackspace.com/archlinux/extra/os/x86_64"
COMRADE_HOME_DIR="${COMRADE_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/comrade-agent}"
SYSROOT="$COMRADE_HOME_DIR/sysroot"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if pkg-config --exists webkit2gtk-4.1 2>/dev/null; then
    echo "webkit2gtk-4.1 already installed system-wide. Nothing to do."
    exit 0
fi

if sudo -n true 2>/dev/null; then
    echo "Installing webkit2gtk-4.1 via pacman..."
    sudo pacman -S --needed --noconfirm webkit2gtk-4.1
    exit 0
fi

# Consolidate a previous rootless install into the comrade-agent home.
if [[ ! -f "$SYSROOT/usr/lib/pkgconfig/webkit2gtk-4.1.pc" ]] \
    && [[ -f "$HOME/comrade-sysroot/usr/lib/pkgconfig/webkit2gtk-4.1.pc" ]]; then
    echo "Moving previous sysroot into $SYSROOT ..."
    mkdir -p "$COMRADE_HOME_DIR"
    mv "$HOME/comrade-sysroot" "$SYSROOT"
fi

if [[ ! -f "$SYSROOT/usr/lib/pkgconfig/webkit2gtk-4.1.pc" ]]; then
    echo "No sudo — fetching webkit2gtk-4.1 into $SYSROOT ..."
    mkdir -p "$SYSROOT"
    cd "$SYSROOT"
    PKG=$(curl -s "$MIRROR/" | grep -o 'webkit2gtk-4\.1-[^"]*\.pkg\.tar\.zst' | sort -u | tail -1)
    if [[ -z "$PKG" ]]; then
        echo "ERROR: could not find webkit2gtk-4.1 on $MIRROR" >&2
        exit 1
    fi
    if [[ ! -f "$PKG" ]]; then
        curl -sO "$MIRROR/$PKG"
    fi
    tar -xf "$PKG"
    if LD_LIBRARY_PATH="$SYSROOT/usr/lib" ldd usr/lib/libwebkit2gtk-4.1.so.0 | grep -q 'not found'; then
        echo "ERROR: missing transitive deps (see above). Install them or run with sudo." >&2
        exit 1
    fi
    cd "$REPO_ROOT"
else
    echo "Vendored webkit already present at $SYSROOT."
fi

mkdir -p "$REPO_ROOT/.cargo"
cat > "$REPO_ROOT/.cargo/config.toml" <<EOF
# Generated by scripts/setup-linux.sh — do not hand-edit.
[env]
PKG_CONFIG_PATH = "$SYSROOT/usr/lib/pkgconfig"

[build]
rustflags = [
    "-C", "link-arg=-L$SYSROOT/usr/lib",
    "-C", "link-arg=-Wl,-rpath,$SYSROOT/usr/lib",
]
EOF

# Rootless WebKit helper shim (LD_PRELOAD redirect for the hard-coded
# /usr/lib/webkit2gtk-4.1 helper path). Only needed when the system copy
# is absent; the app re-execs itself under it automatically.
SHIM_SRC="$REPO_ROOT/shim/webkit-path-shim.c"
SHIM_OUT="$COMRADE_HOME_DIR/shim/webkit-shim.so"
if command -v cc >/dev/null 2>&1 && [[ -f "$SHIM_SRC" ]]; then
    mkdir -p "$(dirname "$SHIM_OUT")"
    cc -shared -fPIC -O2 -o "$SHIM_OUT" "$SHIM_SRC" -ldl \
        && echo "WebKit path shim built: $SHIM_OUT"
else
    echo "WARNING: no C compiler — WebKit shim not built (needs: sudo pacman -S webkit2gtk-4.1)" >&2
fi
echo "Sysroot ready. Build with: cargo build -p comrade-desktop"
